//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATVE
    {
        public int MA_KHACHHANG { get; set; }
        public int MAVE { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VE VE { get; set; }
    }
}
