//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatVeMayBayDBEntities : DbContext
    {
        public DatVeMayBayDBEntities()
            : base("name=DatVeMayBayDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIGHE> LOAIGHEs { get; set; }
        public virtual DbSet<LOAIKHACH> LOAIKHACHes { get; set; }
        public virtual DbSet<MAYBAY> MAYBAYs { get; set; }
        public virtual DbSet<QUOCGIA> QUOCGIAs { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TUYENBAY> TUYENBAYs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
    
        public virtual ObjectResult<Search_Result_final> search(Nullable<System.DateTime> ngaydi, Nullable<int> noidi, Nullable<int> noiden)
        {
            var ngaydiParameter = ngaydi.HasValue ?
                new ObjectParameter("ngaydi", ngaydi) :
                new ObjectParameter("ngaydi", typeof(System.DateTime));
    
            var noidiParameter = noidi.HasValue ?
                new ObjectParameter("noidi", noidi) :
                new ObjectParameter("noidi", typeof(int));
    
            var noidenParameter = noiden.HasValue ?
                new ObjectParameter("noiden", noiden) :
                new ObjectParameter("noiden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result_final>("search", ngaydiParameter, noidiParameter, noidenParameter);
        }
    
        public virtual ObjectResult<danhSachVe_Result> danhSachVe(Nullable<int> chuyenbay, Nullable<int> loaighe)
        {
            var chuyenbayParameter = chuyenbay.HasValue ?
                new ObjectParameter("chuyenbay", chuyenbay) :
                new ObjectParameter("chuyenbay", typeof(int));
    
            var loaigheParameter = loaighe.HasValue ?
                new ObjectParameter("loaighe", loaighe) :
                new ObjectParameter("loaighe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhSachVe_Result>("danhSachVe", chuyenbayParameter, loaigheParameter);
        }
    
        public virtual ObjectResult<danhsachvekhachhang_Result> danhsachvekhachhang(Nullable<int> makhachhang)
        {
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhsachvekhachhang_Result>("danhsachvekhachhang", makhachhangParameter);
        }
    
        public virtual ObjectResult<danhsachvekhdat_Result> danhsachvekhdat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhsachvekhdat_Result>("danhsachvekhdat");
        }
    
        public virtual ObjectResult<getVe_Result> getVe(Nullable<int> machuyen)
        {
            var machuyenParameter = machuyen.HasValue ?
                new ObjectParameter("machuyen", machuyen) :
                new ObjectParameter("machuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getVe_Result>("getVe", machuyenParameter);
        }
    }
}
