//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.CHITIETDATVEs = new HashSet<CHITIETDATVE>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public int MA_KHACHHANG { get; set; }
        public string TEN_KHACHHANG { get; set; }
        public string SDT_KHACHHANG { get; set; }
        public string EMAIL_KHACHHANG { get; set; }
        public Nullable<bool> GIOITINH_KHACHHANG { get; set; }
        public Nullable<bool> TINHTRANG_KHACHHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATVE> CHITIETDATVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
