//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIKHACH
    {
        public int MA_LOAIKHACH { get; set; }
        public string TEN_LOAIKHACH { get; set; }
        public Nullable<float> PHANTRAMGIA_LOAIKHACH { get; set; }
        public Nullable<bool> TINHTRANG_LOAIKHACH { get; set; }
    }
}
