//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANBAY()
        {
            this.TUYENBAYs = new HashSet<TUYENBAY>();
            this.TUYENBAYs1 = new HashSet<TUYENBAY>();
        }
    
        public int MA_SANBAY { get; set; }
        public int MA_QUOCGIA { get; set; }
        public string TEN_SANBAY { get; set; }
        public Nullable<bool> TINHTRANG_SANBAY { get; set; }
        public string DIACHI_SANBAY { get; set; }
    
        public virtual QUOCGIA QUOCGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUYENBAY> TUYENBAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUYENBAY> TUYENBAYs1 { get; set; }
    }
}
