//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MA_TAIKHOAN { get; set; }
        public Nullable<int> MA_KHACHHANG { get; set; }
        public string EMAIL_TAIKHOAN { get; set; }
        public string MATKHAU_TAIKHOAN { get; set; }
        public Nullable<bool> TINHTRANG_TAIKHOAN { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
