//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENBAY()
        {
            this.CHUYENBAYs = new HashSet<CHUYENBAY>();
        }
    
        public int MA_TUYENBAY { get; set; }
        public Nullable<int> MA_SANBAY_DI { get; set; }
        public Nullable<int> MA_SANBAY_DEN { get; set; }
        public string TEN_TUYENBAY { get; set; }
        public string GIOITHIEU_TUYENBAY { get; set; }
        public Nullable<int> GIA_TUYENBAY { get; set; }
        public Nullable<int> THOIGIANBAY { get; set; }
        public string HINHANH_TUYENBAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
    }
}
