//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPlain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE()
        {
            this.CHITIETDATVEs = new HashSet<CHITIETDATVE>();
        }
    
        public int MAVE { get; set; }
        public int MA_CHUYENBAY { get; set; }
        public int MA_GHE { get; set; }
        public Nullable<System.DateTime> NGAYTAO_VE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual GHE GHE { get; set; }
    }
}
